name: terraform-apply

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read
  pull-requests: 'write'
  issues: write

env:
  AWS_REGION: "ap-northeast-1"

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.5

      - name: Configure AWS credentials (apply)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_TERRAFORM_APPLY_ROLE }}
          role-session-name: "gha-terraform-apply"
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: |
          terraform init -migrate-state\
            -backend-config="bucket=${{ secrets.TF_BACKEND_S3_BUCKET }}" \
            -backend-config="key=root/terraform.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}"

      - name: Terraform Validate
        run: terraform validate

      - name: Get pull-request number
        uses: actions/github-script@v8
        id: get_pr_number
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            if ( context.issue.number ) {
              return context.issue.number;
            } else {
              return (
                await github.rest.repos.listPullRequestsAssociatedWithCommit({
                  commit_sha: context.sha,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                })
              ).data[0].number;
            }
          result-encoding: string

      - uses: shmokmt/actions-setup-tfcmt@v2
        with:
          version: v4.13.0

      - name: Terraform Apply
        run: tfcmt apply -- terraform apply -auto-approve
