name: terraform-plan

on:
  pull_request:
    branches: ["main"]

permissions:
  id-token: write
  contents: read
  pull-requests: 'write'

env:
  AWS_REGION: "ap-northeast-1"

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.5

      - name: Configure AWS credentials (plan)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_TERRAFORM_PLAN_ROLE }}
          role-session-name: "gha-terraform-plan"
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: |
          terraform init -migrate-state \
            -backend-config="bucket=${{ secrets.TF_BACKEND_S3_BUCKET }}" \
            -backend-config="key=root/terraform.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}"

      - name: Terraform Validate
        run: terraform validate

      - uses: shmokmt/actions-setup-tfcmt@v2
        with:
          version: v4.13.0

      - name: Terraform Plan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: tfcmt plan --patch -- terraform plan -no-color -input=false
